<?php
/**
 * Created by PhpStorm.
 * User: letsjump
 * Date: 29/10/18
 * Time: 11.28
 */

namespace letsjump\easyAjax;


use letsjump\easyAjax\web\EasyAjaxAsset;
use yii\bootstrap\Modal;
use yii\jui\Widget;

class EasyAjax extends Widget
{
    
    const SUCCESS = 'success';
    
    const MODAL = 'modal',
        MODAL_HEADER = 'header',
        MODAL_CONTENT = 'body',
        MODAL_FOOTER = 'footer',
        MODAL_SIZE = 'size',
        MODAL_ADDCSSCLASS = 'addClass',
        MODAL_CLOSE = 'close',
        GROWL = 'growl',
        TYPE = 'type',
        ICON = 'icon',
        TITLE = 'title',
        JSFUNCTION = 'jsFunction',
        PAGE_REDIRECT = 'redirect',
        PAGE_REDIRECT_AJAX = 'ajaxRedirect',
        PJAX_RELOAD = 'pjaxReload',
        TABS_RELOAD = 'tabsReload',
        FORM_VALIDATION = 'validation',
        CONTENT_REPLACE = 'replace',
        CONFIRM = 'confirm'
    ;
    
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    
    public static function renderModal()
    {
        //EasyAjaxAsset::register( $view );
        Modal::begin([
            'header'  => '<h4 class="modal-title">Title</h4>',
            'footer'  => '',
            'id'      => 'systemModal',
            'size'    => Modal::SIZE_DEFAULT,
            'options' => [
                'tabindex' => false, // important for Select2 to work properly
//            'class' => 'phantomModal',
            ],
        ]);
        echo "<div id='systemModalContent'></div>";
        
        Modal::end();
    }
}