<?php

namespace letsjump\easyAjax\web;

use yii\web\AssetBundle;

/**
 * AdminLte AssetBundle
 *
 * @since 0.1
 */
class EasyAjaxAsset extends AssetBundle
{
    
    public $sourcePath = '@vendor/letsjump/yii2-easy-ajax/assets';
    
    public $js = [
        'yii2-easy-ajax.js'
    ];
    
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        'yii\bootstrap\BootstrapPluginAsset',
    ];
    
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    
}
