<?php

namespace letsjump\easyAjax\web;

use yii\web\AssetBundle;

/**
 * AdminLte AssetBundle
 *
 * @since 0.1
 */
class EasyAjaxAsset extends AssetBundle
{
    
    public $sourcePath = '@vendor/letsjump/yii2-easy-ajax/assets';
    
    public $js = [
        'yii2-easy-ajax.js'
    ];
    
    public $publishOptions = [
        'test' => 'test'
    ];
    
    public $depends = [
        //'rmrevin\yii\fontawesome\AssetBundle',
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        'yii\bootstrap\BootstrapPluginAsset',
    ];
    
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }
    
    public function init()
    {
        $view->registerJsVars('test', 'test');
        parent::init(); // TODO: Change the autogenerated stub
    }
    
}
